name: "Beszel Hub"
version: "0.18.8"
slug: "beszel_hub"
description: "Supervision légère de serveurs avec authentification Home Assistant"
url: "https://github.com/VOX0V/beszel-hub"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 8090
panel: true
options:
  ingress_path: "/api/hassio_ingress/y4kk-clFA5dUphm8XWWK-3gFLB9-xebQbQ6x7dZVDoI"
schema:
  ingress_path: str
map:
  - config:rw
